version: '2.0'

name: "user_auth"


services:
  fastapi_service:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: fastapi_container
    depends_on:
      - postgres_db
    ports:
      - "8000:8000"
    networks:
      - my-api-net
    environment:
      - DATABASE_URL=postgresql://postgres:sweethomealabama@postgres_container:5432/user_auth
      - SECRET_KEY=$(SECRET_KEY)
      - BACKEND_URL= http://0.0.0.0:8000

  postgres_db:
    image: postgres:13
    container_name: postgres_container
    restart: always
    environment:
      - POSTGRES_USER=$(POSTGRES_USER)
      - POSTGRES_PASSWORD=$(POSTGRES_PASSWORD)
      - POSTGRES_DB=$(POSTGRES_DB)
    ports:
      - "5433:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data
    networks:
      - my-api-net


  streamlit:
    image: samdobson/streamlit
    container_name: streamlit_container
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    restart: always
    depends_on:
      - fastapi_service
    ports:
      - "8501:8501"
    networks:
      - my-api-net
    environment:
      - API_URL=http://fastapi_container:8000


volumes:
  postgres_db:
    driver: local

networks:
  my-api-net:
    driver: bridge


