
FROM python:3.12


WORKDIR /frontend

# RUN pip install poetry


# COPY . /pyproject.toml /frontend/


# COPY . /poetry.lock /frontend/


# COPY app/frontend /frontend/


# RUN poetry config virtualenvs.create false


# RUN poetry install 

COPY . /requirements.txt /frontend/

RUN pip install -r requirements.txt


EXPOSE 8501


CMD ["streamlit", "run", "frontend/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
