FROM python:3.11-slim

WORKDIR /app



RUN apt-get update && apt-get install -y --no-install-recommends \
    libpq-dev gcc && \
    rm -rf /var/lib/apt/lists/*



# RUN pip install poetry

COPY requirements.txt /app/
    
# COPY . /pyproject.toml /app/

# COPY . /poetry.lock /app/

RUN pip install --no-cache-dir -r requirements.txt

# COPY wait-for-postgres.sh /app/

# RUN chmod +x /app/wait-for-postgres.sh

COPY . /app /app/

# RUN poetry config virtualenvs.create false

# RUN poetry install --no-root --timeout


EXPOSE 8000

# CMD [ "uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
CMD [ "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]