
FROM python:3.11-slim


WORKDIR /frontend

RUN apt-get update && apt-get install -y --no-install-recommends \
    libpq-dev gcc && \
    rm -rf /var/lib/apt/lists/*


COPY requirements.txt /frontend/

RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt


COPY . /frontend/

EXPOSE 8501

# HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health

ENTRYPOINT ["streamlit", "run", "frontend/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
