FROM python:3.12

WORKDIR /app



RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*



# RUN pip install poetry

COPY . /requirements.txt /app/
    
# COPY . /pyproject.toml /app/

# COPY . /poetry.lock /app/

COPY . /app /app/

RUN pip install -r requirements.txt

# RUN poetry config virtualenvs.create false

# RUN poetry install --no-root --timeout


EXPOSE 8000

CMD [ "uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
