FROM python:3.12

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip install poetry

COPY pyproject.toml poetry.lock /app/

COPY . /app/

RUN poetry config virtualenvs.create false

RUN poetry install 

# COPY app/ /app/app

EXPOSE 8000

CMD ["poetry" "run", "uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
